## Configuring Server Default Port
server:
  port: 8080

spring:   
  datasource:
    url: jdbc:mariadb://localhost:3306/testdb
    username: root
    password: metlife1!
    driver-class-name: "org.mariadb.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MariaDB53Dialect
    hibernate:
      SQL: DEBUG
      ddl-auto: update
      default_schema: testdb
    show-sql: true
    properties:
      hibernate:
        format_sql: true